[libraries]
com-pinterest-ktlint = "com.pinterest:ktlint:0.47.1"
# @pin
org-jetbrains-kotlin-kotlin-bom = "org.jetbrains.kotlin:kotlin-bom:1.7.20"
org-jetbrains-kotlinx-kotlinx-coroutines-bom = "org.jetbrains.kotlinx:kotlinx-coroutines-bom:1.6.4"
org-jetbrains-kotlinx-kotlinx-serialization-bom = "org.jetbrains.kotlinx:kotlinx-serialization-bom:1.4.0"
org-junit-junit-bom = "org.junit:junit-bom:5.9.1"
org-slf4j-slf4j-simple = "org.slf4j:slf4j-simple:2.0.3"

[plugins]
com-github-sghill-distribution-sha = "com.github.sghill.distribution-sha:0.4.0"
de-gliderpilot-semantic-release = "de.gliderpilot.semantic-release:1.4.2"
io-github-gradle-nexus-publish-plugin = "io.github.gradle-nexus.publish-plugin:1.1.0"
nl-littlerobots-version-catalog-update = "nl.littlerobots.version-catalog-update:0.6.1"
